### PR TITLE
Not it branch

### PR DESCRIPTION
**Pull request by perezrei**

### CODE REVIEW

**Review by Fatihayoz — COMMENTED** [review]
I think there is a conflict in the index.html file:
- "The core values" section isn't formatted by Beautify or prettier.
- The contact us section is deleted.

The other parts are OK.

**Comment by Fatihayoz** [comment]
As I try to merge it, there is a message saying:
"Use your administrator privileges to merge this pull request."

**Comment by perezrei** [comment]
Victoria is working in "core values" I haven't check that.
You have to fix the bug with the contact us because you are the administrator. Ask Tamer what can we do. Maybe close the issues  and I make a new PR if you can not fix it

**Review by Fatihayoz — APPROVED** [review]

**Comment by Fatihayoz** [comment]
The conflict is solved. :)

**Pull request merged**
